import { Inter } from '@next/font/google'
import './globals.css'

export const metadata = {
  title: 'V Editor',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  )
}
